// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var etitiesResult = EtitiesResult.FromJson(jsonString);

namespace QuickTypeEtitiesResult
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EtitiesResult
    {
        [JsonProperty("documents")]
        public Document[] Documents { get; set; }

        [JsonProperty("errors")]
        public Error[] Errors { get; set; }
    }

    public partial class Document
    {
        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("entities")]
        public Entity[] Entities { get; set; }
    }

    public partial class Entity
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("matches")]
        public Match[] Matches { get; set; }

        [JsonProperty("wikipediaLanguage")]
        public string WikipediaLanguage { get; set; }

        [JsonProperty("wikipediaId")]
        public string WikipediaId { get; set; }

        [JsonProperty("wikipediaUrl")]
        public Uri WikipediaUrl { get; set; }

        [JsonProperty("bingId")]
        public Guid BingId { get; set; }
    }

    public partial class Match
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("offset")]
        public long Offset { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }
    }

    public partial class Error
    {
        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public partial class EtitiesResult
    {
        public static EtitiesResult FromJson(string json) => JsonConvert.DeserializeObject<EtitiesResult>(json, QuickTypeEtitiesResult.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this EtitiesResult self) => JsonConvert.SerializeObject(self, QuickTypeEtitiesResult.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
